name: docs

on:
  workflow_dispatch:
  push:
    branches:
      - doc
    paths:
      - Project.toml
      - src/**
      - docs/**
      - .github/workflows/docs.yml

jobs:
  # https://github.com/julia-actions/julia-docdeploy
  Documenter:
    permissions:
      contents: write
      statuses: write
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1.11'
          show-versioninfo: true
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-docdeploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
