name: tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - dev
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - Project.toml
      - src/**
      - test/**
      - .JuliaFormatter.toml
      - .github/workflows/tests.yml
  push:
    branches:
      - main
    paths:
      - Project.toml
      - src/**
      - test/**
      - .JuliaFormatter.toml
      - .github/workflows/tests.yml

# https://github.com/julia-actions/julia-runtest
permissions:
  actions: write
  contents: read

jobs:
  test:
    if: ${{ ! github.event.pull_request.draft }}
    strategy:
      matrix:
        test:
          - args: 'lower'
            version: '1.10' # TODO: could that be read from [compat]?
          - args: 'pinned'
            version: '1.11' # TODO: could that be read from pinned env?
          - args: 'latest'
            version: '1'
        os:
         - ubuntu-latest
         - windows-latest
         - macOS-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.test.version }}
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        with:
          test_args: ${{ matrix.test.args }}
